services:
  - type: web
    name: lab-emr-demo
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install --include=dev && npm run prisma:generate --workspace server && npm run build
    preDeployCommand: npm run prisma:push --workspace server && npm run seed --workspace server
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
